### ISSUE TITLE
Can't handle multiple depends from the same file.

### ISSUE THREAD

**Issue by Neppord** [thlorenz/browserify-shim#129]
``` javascript
{
  "browserify-shim": {
    "bootstrap": {"depends": ["jquery:jQuery", "jquery:$"]}
  }
}
```

Seams to break.

**Comment by Neppord** [comment]
There is a workaround for those interested.

By adding 2 aliases:

``` javascript
{
  "browser": {
    "$": "path/to/jquery",
    "jquery": "path/to/jquery"
  },
  "browserify-shim": {
    "bootstrap": {"depends": ["jquery:jQuery", "$:$"]}
  }
}

**Comment by bendrucker** [comment]
Why would you need to do that?

**Comment by Neppord** [comment]
Hi @bendrucker!
 
If you one of your libraries, bootstrap in this example, checks for one and uses the other.

So it checks for the `jQuery` var to see if it exists but then uses `$` for all its manipulations.
check: https://github.com/twbs/bootstrap/blob/master/dist/js/bootstrap.js#L7
usage: https://github.com/twbs/bootstrap/blob/master/dist/js/bootstrap.js#L13

**Comment by bendrucker** [comment]
The syntax on this would be very tricky. Doesn't seem like an especially prominent issue, especially since it's really only going to affect jQuery plugins. If you're up for it, adding the workaround to the [wiki](https://github.com/thlorenz/browserify-shim/wiki/browserify-shim-recipes) seems like the best bet here.
