### ISSUE TITLE
Angular bundle is empty when browserify-shim is added

### ISSUE THREAD

**Issue by demisx** [thlorenz/browserify-shim#131]
Hi. I am trying to make browserify to work with Angular 1.3.11. Currently I have a simple entry point like this:

```js
// app.js
'use strict';
require('angular');
```

As soon as I add this to my package json, angular.js lib disappears from the bundle file. Am I missing something?

```json
// package.json
... ... ...
"browserify-shim": {
    "angular": "global:angular"
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "dependencies": {
    "browserify-shim": "^3.8.0"
  }
```

**Comment by thlorenz** [comment]
That's the point, if you closely read the `global` instructions, you'll see that you have to add angular to your scripts in your `html` file.

**Comment by nkoterba** [comment]
I have a somewhat opposite issue.  

I'm trying to build a vendor and an app bundle.  I'm using browserify-shim to include angular:

package.json:
```javascript
"browser": {
    "angular": "./node_modules/angular/angular.js",
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browserify-shim": {
    "jquery": "jquery",
    "angular": {
      "exports": "angular",
      "depends": [
        "jquery:jQuery"
      ]
    }
}
```

However, when I build my external bundle, angular is not actually exposed so that I can do:

```javascript
var angular = require('angular');
angular.module('myapp', []);
```

in my application bundle.  Angular is always an empty object.

I'm literally trying to get this example/recipe working and it won't work: [recipe](https://github.com/thlorenz/browserify-shim/wiki/browserify-shim-recipes#angular-which-depends-on-jquery--angular-modules-installation-via-npm-and-napa)

**Comment by bendrucker** [comment]
Please open a new issue as this is a completely unrelated topic

**Comment by nkoterba** [comment]
@bendrucker I actually found the exact issue discussed at #134.  Sorry for the cross-issue post.
