### ISSUE TITLE
Unable to make it work with Angular

### ISSUE THREAD

**Issue by blacksonic** [thlorenz/browserify-shim#134]
Tried to shim dependency Angular as mentioned in the recipes section (https://github.com/thlorenz/browserify-shim/wiki/browserify-shim-recipes)
Created also a repo to show it in work (https://github.com/blacksonic/browserify-example)
https://github.com/blacksonic/browserify-example
Angular gets boundled into the vendor bundle with ```require``` and added to the example bundle with ```external```
When i run ```require('angular')``` before the example bundle it works, ```window.angular``` is defined, but ```require('angular')``` always return an empty object

Am i doing something wrong? In the example bundle the ```require``` is replaced with ```if``` clauses but the Angular init code never gets executed.

**Comment by bendrucker** [comment]
This isn't a browserify-shim issue. You're putting Angular off in a browserify wrapper but then shimming the actual `require('angular')` call that would call that wrapper and get the module. So you're creating an external bundle that you can't possible invoke from your main js file because you've shimmed all the calls.

`global:*` is meant for when you're just going to use a plain old script tag. You don't call `exclude` because it's not going be bundle anyway. The `require` gets removed as you'll see in the output bundle.

So you want to either do a global shim and then just concatenate your vendor scripts the old fashion way *or* shim Angular properly and generate the external bundle the way you are now. You can't do both.

**Comment by blacksonic** [comment]
Ok the global way is clear: concat Angular, then use global and requires get replaced.
The other way is to remove ```global:``` and make a shim like: 
```require('angular'); module.exports = angular```
Am i right now?

**Comment by bendrucker** [comment]
https://github.com/bendrucker/browserify-example/commit/2e818437a4eecae3c5583c9f67f1e284780d725b

That's how I'd do it. The global transform option is an unfortunate hack but it should work okay for now. 

I wouldn't worry too much about this fairly brittle solution right now.

https://github.com/angular/angular.js/pull/10732

It's Angular's job to work properly here and export itself. The linked PR is slated for 1.4 which is scheduled for release at ng-conf in less than a month. Hang tight and you'll be able to totally skip browserify-shim for Angular itself and only used it for misbehaved deps.

**Comment by blacksonic** [comment]
Amazing it works! Thanks for the help and guidance.
Looking forward for the 1.4 release

**Comment by nkoterba** [comment]
@bendrucker, @blacksonic Thank you both so much!

Have been spending hours trying to get angular to be properly 'browserify-shim'd in an external vendor bundle.

The code example is very very helpful. I wish I would've found this earlier.

Quick follow-up ?.  So my vendor_bundle contains several 3rd party libraries.  Most of them are CommonJS.  However, a few are not (like angular, kendo, etc.).  By using the "hack":  

```javascript
	b.transform('browserify-shim', {
		global: true
	});
```
will that also cause all of my well-formed CommonJS packages to be exposed globally as well?

If so, is there any way to prevent this? Or do I just wait until 1.4 comes out and hope my other non-CommonJS modules eventually follow UMD as well?

**Comment by bendrucker** [comment]
`global` doesn't mean a global export. It means the transform applies to all files for that bundle instead of just relative requires for that package.

Also Angular isn't doing UMD: https://github.com/angular/angular.js/pull/10732

**Comment by nkoterba** [comment]
@bendrucker Do you know any reason why if I use the `global` condition on the transform that some of my third party libs are "double-shimmed".  For example, when I apply that transform globally for a Kendo UI library I the output below and it errors out on the page because the first `module` reference after the kendo SRC is undefined when used in this code `module.exports = ex`

```javascript
},{}],"kendo":[function(require,module,exports){
(function (global){

; jQuery = global.jQuery = require("jquery");
;__browserify_shim_require__=require;(function browserifyShim(module, exports, require, define, browserify_shim__define__module__export__) {

; jQuery = global.jQuery = __browserify_shim_require__("jquery");
;__browserify_shim_require__=require;(function browserifyShim(module, exports, require, define, browserify_shim__define__module__export__) {
/*
* Kendo UI v2014.3.1411 (http://www.telerik.com/kendo-ui)
* Copyright 2015 Telerik AD. All rights reserved.
*
...
KENDO SRC HERE
...
; browserify_shim__define__module__export__(typeof kendo != "undefined" ? kendo : window.kendo);

}).call(global, undefined, undefined, undefined, undefined, function defineExport(ex) { module.exports = ex; });

; browserify_shim__define__module__export__(typeof kendo != "undefined" ? kendo : window.kendo);

}).call(global, undefined, undefined, undefined, undefined, function defineExport(ex) { module.exports = ex; });

}).call(this,typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})
},{"jquery":"jquery"}]},{},[]);

```

**Comment by bendrucker** [comment]
Probably because you're transforming twice. Don't do that.
