### ISSUE TITLE
Browserify shim does not exports npm modules

### ISSUE THREAD

**Issue by JustBlackBird** [thlorenz/browserify-shim#144]
At the moment there too many packages in npm registry that does not use CommonJS code style. One of such module is `mutationobserver-shim`.

The problem is `browserify-shim` "exports" feature does not work with npm packages. Here is my `package.json`:
```json
{
  "main": "index.js",
  "dependencies": {
    "mutationobserver-shim": "^0.3.1"
  },
  "browserify": {
    "transform": ["browserify-shim"]
  },
  "browserify-shim": {
    "mutationobserver-shim": "MutationObserver"
  },
  "devDependencies": {
    "browserify": "^8.1.3",
    "browserify-shim": "^3.8.2"
  }
}
```

Here is `index.js` file:
```js
var m = require('mutationobserver-shim');
```

To test the problem one can use a command:
```shell
browserify -e index.js -o test.js
```

The resulting `test.js` file have no extra wrapper around contents of `mutationobserver-shim` module although it definitely should.

**Comment by bendrucker** [comment]
See 7c63b7794ceaf35e3a6407e896671647beb05098 which I ended up reverting temporarily. This isn't a b-shim limitation. It has to do with how browserify prevents transforms from affecting `node_modules` to avoid a huge perf overhead. 

See also #143. 

I'm in the process literally right this second of getting Angular fixed in this respect. That should get released later today. First line of attack here is to get package maintainers to fix things from their side. There's a whole bunch of reasons for that. But in the mean time we do want to have good docs on this. If you can dig up other popular offenders it would be a huge help.

**Comment by JustBlackBird** [comment]
Do you mean you want to force package maintainers to follow CommonJS?

**Comment by bendrucker** [comment]
Yes, or at very least provide a CommonJS file as `main`. Not in this case though. I don't understand the point of trying to shim the exports of a shim that's trying to attach itself to something on `window` anyway.

**Comment by JustBlackBird** [comment]
I've got your point though I disagree with it.

You see, there are too many packages in npm and nobody can force their authors to follow CommonJS if they do not want to or just can't by some reasons.

Nevertheless, I'm absolutely fine with the fact b-shim does not work with npm packages without CommonJS support.

**Comment by bendrucker** [comment]
Well it does, it just requires you to run b-shim as a global transform. And in this case there's no point in running b-shim on this mutation shim. If you really want to `require('MutationObserver')`:

```json
{
  "browserify-shim": {
    "MutationObserver": "global:MutationObserver"
  }
}
```

Or just use exposify directly.

And when you build your bundle:

```js
b.add('mutationobserver-shim');
```

Because your code doesn't need to know about any shims, that's a build concern.

**Comment by JustBlackBird** [comment]
Thank you for the guide.
