### ISSUE TITLE
Browserify-shim pure JS

### ISSUE THREAD

**Issue by arb** [thlorenz/browserify-shim#146]
Is there a way to use browserify-shim only via code with no dependency on configuration in "package.json"? I'm trying to generated two bundles and I don't need browserify-shim in a second bundle. The examples always have settings defined in "package.json".

**Comment by bendrucker** [comment]
There isn't a way to handle this at the moment. We're definitely interested in supporting the use of transform options to provide configuration. This isn't especially tricky but there is the issue of merging the config.

**Comment by bendrucker** [comment]
There are a couple of issues that have mentioned this. It's definitely on my list but it's also not something I personally need. A PR would be very welcome.

**Comment by patrickarlt** [comment]
@bendrucker I also need this functionality for building a library that needs a global in one build (using the `--standalone` option) but does not need the global when required normally since global can be required as a CJS module normally.

The API would be pretty simple inspired by babelify:

```js
var browserify = require("browserify");
var browserifyShim = require("browserify-shim");

browserify("./script.js")
  // these override whatever is in package.json
  .transform(browserifyShim.configure({
    "jquery": "$",
    "three": "global:THREE"
  }))
  .bundle()
```

Whatever is passed to `browserifyShim.configure` would override what is in `package.json`. I think this would satisfy both what me and @arb (and @cperryk in #173) need.

I would be happy to work on a PR for this with a little guidance. I'm lost at where you load the `browserify-shim` out of the users `package.json` or does browserify do this for you?

**Comment by bendrucker** [comment]
> I'm lost at where you load the browserify-shim out of the users package.json or does browserify do this for you?

https://github.com/thlorenz/browserify-shim/blob/522038ebb9bacf7fc68712f330dc4c30c01cd882/lib/resolve-shims.js#L158-L213

The upward traversal is handled by mothership

**Comment by bendrucker** [comment]
Also keep in mind that exposify supports transform options. We'd love to have your help on this but if you want to save some time you might want to explore using exposify directly for configurable globals. 

Also never really understood the choice to do a proprietary transform config api instead of using options.

**Comment by patrickarlt** [comment]
> if you want to save some time you might want to explore using exposify directly for configurable globals

Turns out this is exactly what I need. This will build a standalone build of my library at `window.L.esri` and it expects `window.L` to be created by a script tag and Leaflet is not included in my build.

```js
var browserify = require('browserify');
var fs = require('fs');
var path = require('path');

browserify('./src/EsriLeaflet.js', {
  debug: true,
  standalone: 'L.esri'
})
.transform('babelify')
.transform('exposify', { expose: { leaflet: 'L' } })
.bundle()
.pipe(fs.createWriteStream(path.join(__dirname, './dist/esri-leaflet-src.js'), 'utf8'))
```

> Also never really understood the choice to do a proprietary transform config api instead of using options

Now that I've brushed up on this this approach makes a lot more sense. Thanks for your help @bendrucker.

**Comment by bendrucker** [comment]
:+1:! I'm using browserify-shim for a work project so I might get around to a cleanup.
