### ISSUE TITLE
Should allow shim configuration settings outside of package.json

### ISSUE THREAD

**Issue by mitermayer** [thlorenz/browserify-shim#187]
I am struggling to understand why do we have to set the shims on the package.json. Is there another way to do the same thing ?

**Comment by mitermayer** [comment]
Would be great if that could be done via a configuration when requiring browserify-shim.

```
var shim = require('browserify-shim").configure({
    ...
});

// this would allow us to do that
 browserify({
    entries: './entry.js',
    debug: true,
    transforms: [shim, reactify, babelify]  });

```

**Comment by bendrucker** [comment]
The right API for this is described in #146. It would be a pretty significant change and I highly doubt either Thorsten or I will have the time anytime soon to overhaul everything to support transform options. We'd need someone to step up in a big way on a PR here. It's hard for me to justify spending huge amounts of time on stuff like this since I've mitigated the need to use b-shim and see a lot of people doing the same.

**Comment by kolya-ay** [comment]
@mitermayer, you could just use [exposify](https://github.com/thlorenz/exposify) for that.
