### ISSUE TITLE
Absolute Paths being used as shim aliases?

### ISSUE THREAD

**Issue by jquense** [thlorenz/browserify-shim#43]
I'm running into a sitution where I have two shimmed bundles like:

```
"browser": {
  "jquery": "./Scripts/lib/jquery-1.8.2.js",
  "kendo-web": "./Scripts/lib/kendo.web.js",
  "report-viewer": "./Scripts/lib/ReportViewer-8.0.14.225.js"
},
"browserify-shim": {
  "jquery": "$",
  "kendo-web": { "exports": "kendo", "depends": [ "jquery:jQuery"] },
  "report-viewer": {
    "exports": "telerikReportViewer",
    "depends": [
      "jquery:jQuery",
      "kendo-web:kendo"
    ]
  }
}
```

running `browserify -r ./Scripts/lib/ReportViewer-8.0.14.225.js -o libs.js` is resulting in the kendo-web dep to output in lib.js as

```
kendo = global.kendo = require("C:\\Projects\\Scripts\\lib\\kendo.web.js");
```

the issue being i'm not super excited about exposing fs structure here when it isn't necessary? I am not sure why it isn't just using `require('kendo-web')` any thoughts on what is happening, has it always worked like this and i didn't notice? i'm using the latest version of browserify-shim

**Comment by eggyal** [comment]
It should be possible to insert intreq into the browserify compiler pipeline, rather than performing via a transformation after unpacking (and then repacking once done).  Can't find anything resembling guidance on how to do this, though...

**Comment by StreetStrider** [comment]
Hmm. I've faced this issue today. I think @ennovum is correct here,
> AFAIK browserify uses full file paths as keys of the resolved files map, but it is browserify-shim that exposes it.

When I'm using shimed modules with deps from another shimmed modules that gave me a bunch of my-homedir-ish paths in my bundle (my project is somewhere under my homedir). This looks weird when my username draws in bundle, so I start digging. I start with `intreq` (mentioned above) and [unpathify](https://www.npmjs.com/package/unpathify) and end with [**bundle-collapser**](https://www.npmjs.com/package/bundle-collapser). If someone find this useful, bundle-collapser is OK, but note for devs who use multiple bundles with external deps: you can't collapse bundle which is a dep for another, since they will have uncorrelating ids for modules.

You can use collapser only on the «main» bundle which depends on others.
