### ISSUE TITLE
'Cannot find module' for Globals

### ISSUE THREAD

**Issue by ryan-kimber** [thlorenz/browserify-shim#46]
I've been trying to create a project that utilizes AngularJS, Browserify and Gulp for an excellent developer experience, one that produces a distributable 'module' (in Angular parlance).

We've had great results with Gulp, but we're having trouble with browserify-shim. Also, unfortunately, most of the examples out there either don't use gulp, or use gulp-browserify, which has been blacklisted/ended.

We're including AngularJS and JQuery from Google CDN as &lt;script&gt; tags and have declared "angular" : "global:angular" and "jquery" : "global:$" in our browserify-shim config in package.json, but we're getting "cannot find module" when we try to user var angular = require('angular') and var $ = require('jquery') inside of our browserified-code (once it runs in the browser). 

I've created a sample project that distills this down close to the minimum. 
It's available at https://github.com/ryan-kimber/multi-browserify 
Once cloned, you would run 'npm install', then 'bower install', then 'gulp' to generate the files and run the test server. You can access the live HTML at http://localhost:4000/gulp.html

Any help would be appreciated, but I'm also wondering if we've come across a bug/issue with the intersection of gulp, browserify, vinyl-source-stream, etc.

**Comment by jamiis** [comment]
any news?

**Comment by bendrucker** [comment]
No. When we have a chance to look at @markreid's repo and hopefully resolve this you'll hear.

**Comment by rahulbpatel** [comment]
If this helps anyone, I used the following to be able to include jQuery from a CDN but still have the ability to use `require('jquery')` in CommonJS modules via Globals

**package.json**
```javascript
"browser": {
        "jquery": "./client/src/js/jquery_shim.js"
    },
"browserify": {
    "transform": [
        "browserify-shim"
    ]
},
"browserify-shim": {
    "jquery": "global:jQuery"
}
```
**jquery_shim.js**
```javascript
module.exports = require('jquery');
```
**index.html**
```HTML
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="/js/bundle.js"></script>
```

**Comment by eliot-akira** [comment]
I am having the same issue as the original poster: cannot find module 'jquery', even though it's specified as a global in package.json:

```
"browserify": {
    "transform": [
        "browserify-shim"
    ]
},
"browserify-shim": {
    "jquery": "global:jQuery"
}
```

And requiring it with:

```
var $ = require('jquery');
```

The twist in my situation is, the above was working fine until I decided to move *package.json* and *node_modules* into a subdirectory rather than root folder. I'm using Gulp and have configured the tasks to reflect the change in location - everything works except for the error: Cannot find module 'jquery' from (path to the JS file which requires it).

So I have to work around the issue with:

```
var $ = window.jQuery;
```

**Comment by bendrucker** [comment]
@eliot-akira Your issue is not related. You cannot put your package.json and node_modules folder below the working directory. It will break all kinds of things.

**Comment by eliot-akira** [comment]
Everything works fine (concat, uglify, etc.) except for the global shim not being resolved. The only difference is that the dest/target folder is a sibling folder instead of child. I traced it to `resolveShims()` where it looks for *package.json* to load config..and realized you're right. It needs to be in the same folder or one of the parent folders of the JS file being shimmed. Ah, such an obvious mistake. I moved *package.json* to the assets folder, and the shim is applied as expected. I don't know if this is standard practice (node_modules/package.json/gulpfile.js under /assets) but for this project all build happens there, and it keeps the root directory clean.

**Comment by Strajk** [comment]
It's probably little bit different problem, but this Issue came up first in Google for this problem so I will share what helped me:

My problem was:
My modules are placed in `scripts/` folder, lot of them requires jquery `require('jquery')`, but I need jQuery to be global, so I include jQuery via normal script tag and shim it with browserify-shim like `"browserify-shim": { "jquery": "global:$" }` ... this works fine for my module placed in `scripts/` directory

But if any of modules in node_modules requires jquery, browserify will fail with `
Cannot find module 'jquery'`

Solution 1:
Create jquery shim module with just index.js and `npm install it`
```
module.exports = window.jQuery;
```

Solution 2:
npm install jquery so it's in node_modules and use it in script tag. This wouln't normally work because node_modules probably should be publicly accessible on server. But you can use e.g. grunt-usemin to bundle it in build step
```
// build:js /scripts/vendor.js
script(src='../node_modules/jquery/jquery.js')
...
// endbuild
```


But still, would be nice if browserify-shim would also "apply" for dependencies in node_modules

**Comment by Strajk** [comment]
Also I spent a lot of time with debugging why Solution 2 wasn't working for me, and it was because I'm using jQuery 1.8.2 which doesn't have main field in package.json (see https://github.com/jquery/jquery/blob/1.8.2/package.json), so browserify was looking for index.js, but jquery iteself is in jquery.js ... My solution (with which I'm not happy) was to fork jquery 1.8.2 and add `"main": "jquery.js"` to package.json

**Comment by bendrucker** [comment]
@Strajk Your problem is not related. Browserify transforms do not run on code from `node_modules`, otherwise your build you take forever. 

https://github.com/substack/node-browserify#btransformtr-opts, look for `opts.global`.

**Comment by chetzof** [comment]
Can confirm the issue
``` 
 "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
 "browserify-shim": {
    "jquery": "global:$"
  }
```

works fine for everything EXCEPT node modules that have jquery as dependency
```
Error Cannot find module 'jquery' from '/proj/node_modules/slick-carousel/slick'

```

**Comment by thlorenz** [comment]
Those modules are inherently broken if they `require` jquery but don't list and thus install it as a dependency in the `package.json`.

You should file an issue with those modules.

**Comment by Strajk** [comment]
> but don't list and thus install it as a dependency in the package.json.

@thlorenz can you please explain this a little bit?

**Comment by bendrucker** [comment]
If you have a package that is calling `require('jquery')` but jquery is not a dependency of those modules, that package is broken. 

Seems like a lot of recent issues are due to a misunderstanding of how transforms work in Browserify. See #144 for an example.

**Comment by temoto** [comment]
:+1: affects me
jquery_shim.js solution by @rahulbpatel works, thank you.

**Comment by bendrucker** [comment]
The only commonality here seems to be jQuery. There are several separate issues here. 

For anyone arriving, please open a new issue with a clear reproduction of the problem.
