### ISSUE TITLE
Api in V3

### ISSUE THREAD

**Issue by mbrevda** [thlorenz/browserify-shim#56]
There is a branch with an example on how to use the api in v2. Can the same be done in v3? How?

**Comment by romeovs** [comment]
I'm also a fan of having the programmatic api. The reason being that it is programmatic. I have a pretty complicated gulp setup that does different thing based on flags like `--production` etc. The configuration for `browserify-shim` needs to be different based on which flags are set. Another thing is that I would like to write a browserify plugin that is a simple wrapper for `browserify-shim` but that does some extra stuff, right now there's no way to do that because I cannot change the configuration that the user has provided and pass the changed config.
